import type { DocumentCapabilityDef } from '../capabilities/capability.types'

export const DOCUMENT_STUDIO_CAPABILITIES: DocumentCapabilityDef[] = [
  {
    id: 'generate-general-document',
    label: '通用文稿生成',
    description: '根据需求生成通用文稿初稿',
    runner: 'opencode',
    skillId: 'general-document-writer',
    actionType: 'generate_document',
    scope: 'document',
    outputMode: 'new_artifact',
    documentTypes: ['general'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'generate-news',
    label: '新闻稿生成',
    description: '根据活动信息和材料生成正式新闻稿',
    runner: 'opencode',
    skillId: 'news-writer',
    actionType: 'generate_document',
    scope: 'document',
    outputMode: 'new_artifact',
    documentTypes: ['news'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'generate-report',
    label: '汇报材料生成',
    description: '根据要点生成汇报材料初稿',
    runner: 'opencode',
    skillId: 'general-document-writer',
    actionType: 'generate_document',
    scope: 'document',
    outputMode: 'new_artifact',
    documentTypes: ['report'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'generate-notice',
    label: '通知公告生成',
    description: '生成正式通知公告',
    runner: 'opencode',
    skillId: 'general-document-writer',
    actionType: 'generate_document',
    scope: 'document',
    outputMode: 'new_artifact',
    documentTypes: ['notice'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'generate-minutes',
    label: '会议纪要生成',
    description: '根据会议信息生成纪要初稿',
    runner: 'opencode',
    skillId: 'general-document-writer',
    actionType: 'generate_document',
    scope: 'document',
    outputMode: 'new_artifact',
    documentTypes: ['minutes'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'rewrite-selection',
    label: '改写',
    description: '保持原意，重新组织选中文本表达',
    runner: 'direct-llm',
    actionType: 'transform_selection',
    scope: 'selection',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'continue-writing',
    label: '续写',
    description: '根据上下文继续写作',
    runner: 'direct-llm',
    actionType: 'continue_writing',
    scope: 'block',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'polish-selection',
    label: '润色',
    description: '优化表达，保持原意',
    runner: 'direct-llm',
    actionType: 'transform_selection',
    scope: 'selection',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'rephrase-selection',
    label: '重写',
    description: '用不同表述重写选中文本',
    runner: 'direct-llm',
    actionType: 'transform_selection',
    scope: 'selection',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'translate-selection',
    label: '翻译',
    description: '翻译选中文本',
    runner: 'direct-llm',
    actionType: 'transform_selection',
    scope: 'selection',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'summarize-document',
    label: '生成摘要',
    description: '为全文生成摘要',
    runner: 'direct-llm',
    actionType: 'transform_document',
    scope: 'document',
    outputMode: 'comments',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'humanize-selection',
    label: 'AI降重',
    description: '减少重复表达、优化句式、降低模板化痕迹，保留原意',
    runner: 'direct-llm',
    skillId: 'humanizer',
    actionType: 'transform_selection',
    scope: 'selection',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'humanize-document-advanced',
    label: '高级AI降重',
    description: '使用 humanizer skill 对长文或全文进行自然化改写',
    runner: 'opencode',
    skillId: 'humanizer',
    actionType: 'transform_document',
    scope: 'document',
    outputMode: 'patch',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'academic-paper-pipeline',
    label: '论文写作',
    description: '多阶段学术写作流程（待接入 Skill）',
    runner: 'pipeline',
    skillId: 'academic-research-skills',
    actionType: 'generate_document',
    scope: 'pipeline',
    outputMode: 'new_artifact',
    documentTypes: ['paper'],
    enabled: false,
    status: 'pending',
  },
  {
    id: 'academic-review',
    label: '学术审阅',
    description: '对论文文稿给出审阅意见（实验性）',
    runner: 'opencode',
    skillId: 'academic-research-skills',
    actionType: 'review_document',
    scope: 'document',
    outputMode: 'comments',
    documentTypes: ['paper'],
    enabled: false,
    status: 'pending',
  },
  {
    id: 'export-markdown',
    label: '导出 Markdown',
    description: '导出 Markdown 文件',
    runner: 'node',
    actionType: 'export_document',
    scope: 'document',
    outputMode: 'export',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'export-html',
    label: '导出 HTML',
    description: '导出 HTML 文件',
    runner: 'node',
    actionType: 'export_document',
    scope: 'document',
    outputMode: 'export',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'export-docx',
    label: '导出 Word',
    description: '从 editorJson 导出 DOCX（标题、标题级、段落、列表、加粗/斜体）',
    runner: 'node',
    actionType: 'export_document',
    scope: 'document',
    outputMode: 'export',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: true,
    status: 'connected',
  },
  {
    id: 'export-pdf',
    label: '导出 PDF',
    description: '导出 PDF（待接入 Playwright）',
    runner: 'node',
    actionType: 'export_document',
    scope: 'document',
    outputMode: 'export',
    documentTypes: ['general', 'news', 'report', 'notice', 'minutes', 'summary', 'research', 'proposal', 'paper'],
    enabled: false,
    status: 'pending',
  },
]

export function getDocumentStudioCapability(id: string): DocumentCapabilityDef | undefined {
  return DOCUMENT_STUDIO_CAPABILITIES.find(c => c.id === id)
}

export function listCapabilitiesForDocumentType(documentType: string): DocumentCapabilityDef[] {
  return DOCUMENT_STUDIO_CAPABILITIES.filter(
    c => c.documentTypes.includes(documentType) && c.status !== 'legacy-hidden',
  )
}
