import type { WebDocumentSkillManifest } from './webDocumentSkillTypes'
import { DEFAULT_PAGE_SPEC, EMPTY_HEADER_FOOTER } from './webDocumentTypes'

const A4 = { ...DEFAULT_PAGE_SPEC }

export const WEB_DOCUMENT_BUILTIN_SKILLS: WebDocumentSkillManifest[] = [
  {
    id: 'document.generator.office_draft',
    kind: 'document-generator',
    name: '通用正式文稿生成',
    description: '根据要求与资料生成正式办公文稿正文',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.docx.create',
    capability: 'generate-formal-document',
  },
  {
    id: 'document.template.general',
    kind: 'document-template',
    name: '普通文稿',
    description: 'A4 普通文稿，简洁页眉页脚',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    pageSpec: A4,
    headerFooter: {
      ...EMPTY_HEADER_FOOTER,
      showPageNumber: true,
      footerText: '第 {page} 页',
      footerAlign: 'center',
    },
    bodySlots: [{ id: 'body', label: '正文', editable: true }],
  },
  {
    id: 'document.template.formal_letter',
    kind: 'document-template',
    name: '正式函件',
    description: '函件版式：标题、正文、落款区',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    pageSpec: A4,
    headerFooter: {
      showPageNumber: true,
      headerText: '正式函件',
      headerAlign: 'center',
      footerText: '— {page} —',
      footerAlign: 'center',
    },
    bodySlots: [
      { id: 'title', label: '标题', editable: true },
      { id: 'body', label: '正文', editable: true },
      { id: 'signature', label: '落款', editable: true },
    ],
  },
  {
    id: 'document.template.work_report',
    kind: 'document-template',
    name: '工作汇报',
    description: '汇报类页眉与页码',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    pageSpec: A4,
    headerFooter: {
      showPageNumber: true,
      headerText: '工作汇报',
      headerAlign: 'left',
      footerText: '内部资料 · 第 {page} 页',
      footerAlign: 'right',
    },
    bodySlots: [{ id: 'body', label: '汇报正文', editable: true }],
  },
  {
    id: 'document.export.docx',
    kind: 'document-exporter',
    name: '导出 Word',
    description: '按当前版式导出 .docx',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.docx.export',
    outputFormats: ['docx'],
  },
  {
    id: 'document.export.pdf',
    kind: 'document-exporter',
    name: '导出 PDF',
    description: '按当前版式导出 PDF（需服务配置）',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.pdf.export',
    outputFormats: ['pdf'],
  },
  {
    id: 'document.export.markdown',
    kind: 'document-exporter',
    name: '导出 Markdown',
    description: '导出 Markdown 文稿',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.markdown.export',
    outputFormats: ['md'],
  },
  {
    id: 'document.import.word_reference',
    kind: 'document-importer',
    name: '导入 Word 资料',
    description: '上传 docx 作为生成参考资料',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.word.import.reference',
    inputFormats: ['docx'],
  },
  {
    id: 'document.import.pdf_reference',
    kind: 'document-importer',
    name: '导入 PDF 资料',
    description: '上传 pdf 作为生成参考资料',
    version: '1.0.0',
    enabled: true,
    builtin: true,
    mapsToSkillId: 'web.pdf.import.reference',
    inputFormats: ['pdf'],
  },
]

export function getBuiltinDocumentSkill(id: string): WebDocumentSkillManifest | undefined {
  return WEB_DOCUMENT_BUILTIN_SKILLS.find((s) => s.id === id)
}
