import type {
  DailyResearchReport,
  ExperimentNotebookEntry,
  ExperimentPlan,
  LocalScienceCapability,
  PersonalKnowledgeSnapshot,
  ResearchDataAnalysisSnapshot,
  ResearchField,
  ResearchIdeaCard,
  ResearchMatter,
  ResearchPaperRef,
  ResearchSubscription,
  ResearchWorkspaceState,
  ResearchWritingTask,
} from './types'

export const researchFields: ResearchField[] = [
  {
    id: 'ai-for-science',
    name: 'AI for Science',
    description: '聚焦科学发现中的基础模型、实验自动化与科学推理闭环。',
    tags: ['foundation model', 'scientific reasoning', 'lab automation'],
    difficulty: 'advanced',
    recommendedFor: ['跨学科研究者', '算法工程师', '实验平台负责人'],
  },
  {
    id: 'medical-imaging',
    name: '医学影像分析',
    description: '面向 CT、MRI、病理切片与多模态影像的诊断和预测建模。',
    tags: ['CT', 'MRI', 'pathology'],
    difficulty: 'intermediate',
    recommendedFor: ['医学 AI 团队', '影像科协作项目', '临床科研新人'],
  },
  {
    id: 'bioinformatics',
    name: '生物信息学',
    description: '结合组学数据、蛋白结构与功能注释做机制发现与靶点筛选。',
    tags: ['multi-omics', 'protein', 'single-cell'],
    difficulty: 'advanced',
    recommendedFor: ['计算生物学研究者', '药企算法团队'],
  },
  {
    id: 'drug-discovery',
    name: '药物发现',
    description: '从靶点发现到分子生成和体外验证的 AI 驱动研发流程。',
    tags: ['target discovery', 'molecule generation', 'screening'],
    difficulty: 'advanced',
    recommendedFor: ['新药研发团队', '化学生物学研究者'],
  },
  {
    id: 'multimodal-medical-llm',
    name: '多模态医疗大模型',
    description: '连接病历、影像、检验与指南，构建临床辅助决策能力。',
    tags: ['multimodal', 'clinical records', 'VLM'],
    difficulty: 'advanced',
    recommendedFor: ['医院信息化团队', '医疗大模型研发者'],
  },
  {
    id: 'robotic-lab',
    name: '机器人与实验自动化',
    description: '围绕高通量实验、自动配液与闭环优化搭建实验工作流。',
    tags: ['robotics', 'closed-loop', 'high-throughput'],
    difficulty: 'intermediate',
    recommendedFor: ['自动化实验室', '材料/化学平台'],
  },
  {
    id: 'materials-computing',
    name: '材料科学计算',
    description: '使用模拟、代理模型与主动学习寻找更优结构和工艺窗口。',
    tags: ['materials design', 'simulation', 'active learning'],
    difficulty: 'advanced',
    recommendedFor: ['材料计算团队', '能源器件研发'],
  },
  {
    id: 'brain-cognition',
    name: '脑科学与认知计算',
    description: '连接神经数据、行为实验与认知建模，探索脑机制和智能启发。',
    tags: ['EEG', 'fMRI', 'cognition'],
    difficulty: 'intermediate',
    recommendedFor: ['神经科学实验室', '认知计算方向学生'],
  },
]

export const researchSubscriptions: ResearchSubscription[] = [
  {
    id: 'sub-aifs-foundation',
    title: 'AI for Science 基础模型追踪',
    type: 'field',
    query: 'AI for Science foundation model scientific reasoning',
    enabled: true,
    paperCount: 26,
    lastUpdatedAt: '2026-05-24T08:40:00.000Z',
  },
  {
    id: 'sub-drug-keyword',
    title: '药物发现关键词订阅',
    type: 'keyword',
    query: 'retrieval augmented drug discovery benchmark',
    enabled: true,
    paperCount: 14,
    lastUpdatedAt: '2026-05-24T07:55:00.000Z',
  },
  {
    id: 'sub-author-zitnik',
    title: '作者订阅：Marinka Zitnik',
    type: 'author',
    query: 'Marinka Zitnik',
    enabled: true,
    paperCount: 9,
    lastUpdatedAt: '2026-05-23T23:10:00.000Z',
  },
  {
    id: 'sub-neurips-datasets',
    title: '会议订阅：NeurIPS Datasets & Benchmarks',
    type: 'conference',
    query: 'NeurIPS Datasets and Benchmarks',
    enabled: false,
    paperCount: 7,
    lastUpdatedAt: '2026-05-22T18:30:00.000Z',
  },
  {
    id: 'sub-nmi-journal',
    title: '期刊订阅：Nature Machine Intelligence',
    type: 'journal',
    query: 'Nature Machine Intelligence',
    enabled: true,
    paperCount: 11,
    lastUpdatedAt: '2026-05-24T06:20:00.000Z',
  },
]

export const researchPaperRefs: ResearchPaperRef[] = [
  {
    id: 'paper-cell-diffusion',
    title: 'Cell-conditioned diffusion priors for microscopy-guided perturbation screening',
    authors: ['A. Romero', 'M. Xu', 'J. Lee'],
    venue: 'Nature Methods',
    year: 2026,
    abstract: '提出将细胞显微图像与扰动条件联合编码，用于预测潜在药物作用路径并减少湿实验筛选轮次。',
    tags: ['cell imaging', 'diffusion prior', 'screening'],
    relevanceScore: 95,
  },
  {
    id: 'paper-med-vlm',
    title: 'Clinical vision-language pretraining for longitudinal CT progression modeling',
    authors: ['Y. Wang', 'S. Patel', 'R. Gupta'],
    venue: 'MICCAI',
    year: 2026,
    abstract: '利用纵向 CT 与病历联合预训练提升疾病进展预测和治疗响应估计。',
    tags: ['CT', 'vision-language', 'longitudinal'],
    relevanceScore: 92,
  },
  {
    id: 'paper-omics-agent',
    title: 'Agentic multi-omics retrieval improves pathway hypothesis generation',
    authors: ['L. Chen', 'P. Singh', 'M. Zitnik'],
    venue: 'ICLR',
    year: 2026,
    abstract: '构建多组学检索代理，在假说生成时显式对齐通路证据和既有文献。',
    tags: ['multi-omics', 'retrieval', 'agent'],
    relevanceScore: 90,
  },
  {
    id: 'paper-robotic-lab',
    title: 'Closed-loop robotic experimentation with uncertainty-aware active learners',
    authors: ['D. Foster', 'K. Nakamura', 'J. Qian'],
    venue: 'Science Robotics',
    year: 2025,
    abstract: '机器人实验平台与主动学习器协同，能在预算受限条件下优先探索高信息增益实验。',
    tags: ['robotics', 'active learning', 'closed-loop'],
    relevanceScore: 88,
  },
  {
    id: 'paper-material-graph',
    title: 'Graph surrogate models for fast electrolyte composition search',
    authors: ['H. Müller', 'F. Zhou', 'N. Chen'],
    venue: 'Advanced Materials',
    year: 2025,
    abstract: '通过图代理模型快速估计电解液配方性能，缩短实验搜索周期。',
    tags: ['materials', 'graph model', 'electrolyte'],
    relevanceScore: 85,
  },
  {
    id: 'paper-brain-foundation',
    title: 'A foundation encoder for EEG-fMRI alignment under cognitive load',
    authors: ['C. Rivera', 'T. Zhao', 'E. Holmes'],
    venue: 'NeurIPS',
    year: 2025,
    abstract: '统一编码 EEG 与 fMRI 信号，用于认知负荷估计和跨模态脑信号检索。',
    tags: ['EEG', 'fMRI', 'foundation encoder'],
    relevanceScore: 83,
  },
  {
    id: 'paper-drug-retrosynthesis',
    title: 'Retrieval-augmented retrosynthesis planning with assay-aware constraints',
    authors: ['R. Banerjee', 'J. Li', 'C. Davis'],
    venue: 'ICML',
    year: 2026,
    abstract: '引入体外 assay 约束到 retrosynthesis 规划，减少无法验证的候选路线。',
    tags: ['retrosynthesis', 'retrieval', 'assay'],
    relevanceScore: 91,
  },
  {
    id: 'paper-medical-kg',
    title: 'Patient-specific medical knowledge graphs for multimodal treatment planning',
    authors: ['K. Sun', 'M. Ahmed', 'Q. Luo'],
    venue: 'Nature Digital Medicine',
    year: 2026,
    abstract: '患者级知识图谱连接影像、实验室指标和指南，支持个性化治疗计划生成。',
    tags: ['knowledge graph', 'multimodal medicine', 'planning'],
    relevanceScore: 89,
  },
]

export const researchIdeaCards: ResearchIdeaCard[] = [
  {
    id: 'idea-cell-perturbation',
    title: '把显微扰动图像与单细胞通路检索结合，生成更可解释的药物作用假说',
    field: 'AI for Science',
    sourcePapers: [researchPaperRefs[0], researchPaperRefs[2]],
    coreObservation: '最新工作开始把显微表型和组学检索放在同一个推理链中，但实验解释层仍然薄弱。',
    researchGap: '多数方法只能输出候选分子或候选通路，难以说明哪一类细胞状态变化真正驱动结论。',
    hypothesis: '如果把显微图像中的形态变化映射到单细胞 pathway retrieval 证据，可显著提升扰动筛选的可解释性。',
    possibleMethod: '构建图像编码器 + 通路检索器的双塔结构，并用细胞状态伪标签进行跨模态对齐。',
    requiredData: ['显微扰动图像', '单细胞 RNA-seq 数据', '药物-通路注释表'],
    requiredExperiment: ['小规模扰动复现实验', '通路富集验证', '对照组解释一致性分析'],
    feasibilityScore: 82,
    noveltyScore: 88,
    riskLevel: 'medium',
    nextAction: 'make_plan',
  },
  {
    id: 'idea-ct-progress',
    title: '用纵向 CT + 病历时间线预测治疗响应窗口，而不是只做单次诊断分类',
    field: '医学影像分析',
    sourcePapers: [researchPaperRefs[1], researchPaperRefs[7]],
    coreObservation: '多模态医疗模型已经能做静态判断，但真正支持临床决策的时间线推理还很少。',
    researchGap: '缺少同时建模影像变化速度、治疗干预节点和个体化病历上下文的统一框架。',
    hypothesis: '纵向影像与事件时间线联合编码，可提前识别治疗响应拐点并优化复查间隔。',
    possibleMethod: '构建时间感知视觉-文本 Transformer，并引入病程事件图做时间注意力偏置。',
    requiredData: ['纵向胸部 CT', '放疗/化疗事件时间线', '出院小结与检验指标'],
    requiredExperiment: ['时间窗 ablation', '病程事件扰动实验', '医生对关键帧打分'],
    feasibilityScore: 76,
    noveltyScore: 84,
    riskLevel: 'medium',
    nextAction: 'read_more',
  },
  {
    id: 'idea-assay-aware-retro',
    title: '把 assay 约束提前注入逆合成规划，减少后期无法验证的候选路线',
    field: '药物发现',
    sourcePapers: [researchPaperRefs[6], researchPaperRefs[2]],
    coreObservation: '当前逆合成规划更擅长生成路线，而不是生成可直接进入验证环节的路线。',
    researchGap: '实验 assay 条件和生物活性筛选信息往往在路线生成后才被考虑。',
    hypothesis: '在规划阶段显式加入 assay 约束，可以提升可落地路线占比并减少化学合成返工。',
    possibleMethod: '用检索增强的规划器读取历史 assay 失败案例，对候选路线做约束排序。',
    requiredData: ['历史合成路线', 'assay 条件表', '活性筛选结果'],
    requiredExperiment: ['离线回放评测', '资深化学家盲评', '小规模 wet-lab 验证'],
    feasibilityScore: 79,
    noveltyScore: 81,
    riskLevel: 'low',
    nextAction: 'write_proposal',
  },
  {
    id: 'idea-robotic-material',
    title: '让机器人实验平台根据材料代理模型的不确定性自动选择下一批实验',
    field: '机器人与实验自动化',
    sourcePapers: [researchPaperRefs[3], researchPaperRefs[4]],
    coreObservation: '闭环实验平台已可自动执行，但还缺少面向材料工艺窗口的优先级策略。',
    researchGap: '主动学习策略和实验平台日志没有深度耦合，实验失败信息无法及时反哺采样器。',
    hypothesis: '如果将实验失败类型编码进代理模型，可在同样预算下更快收敛到高性能配方。',
    possibleMethod: '设计 uncertainty-aware sampler，并将机器人执行日志转为 failure tokens 参与训练。',
    requiredData: ['机器人执行日志', '材料配方参数', '性能测量结果'],
    requiredExperiment: ['闭环平台仿真', '失败样本重加权实验', '真实平台小批量试跑'],
    feasibilityScore: 74,
    noveltyScore: 86,
    riskLevel: 'high',
    nextAction: 'run_experiment',
  },
  {
    id: 'idea-brain-alignment',
    title: '基于 EEG-fMRI 联合编码做认知负荷早期识别，并探索可解释脑区贡献',
    field: '脑科学与认知计算',
    sourcePapers: [researchPaperRefs[5], researchPaperRefs[7]],
    coreObservation: '跨模态脑信号编码有了基础模型雏形，但用于具体认知任务时可解释性不够。',
    researchGap: '脑区贡献和行为结果之间的桥接层不足，难以形成可写进论文的机制讨论。',
    hypothesis: '如果把脑区先验作为注意力约束，联合编码器能在认知负荷识别上提升稳定性和解释性。',
    possibleMethod: '构建脑区掩码引导的 cross-modal attention，并在行为任务上做脑区贡献分析。',
    requiredData: ['EEG-fMRI 同步数据', '行为任务记录', '脑区模板'],
    requiredExperiment: ['脑区先验对照实验', '不同任务迁移实验', '专家脑区解释核查'],
    feasibilityScore: 71,
    noveltyScore: 83,
    riskLevel: 'medium',
    nextAction: 'make_plan',
  },
]

export const dailyResearchReport: DailyResearchReport = {
  id: 'report-2026-05-24',
  date: '2026-05-24',
  summary: '今天新增文献主要集中在科学基础模型、纵向医疗建模和实验自动化。结合你的个人知识库，最值得追踪的是“可解释的跨模态假说生成”和“实验失败信号如何反哺下一轮实验设计”。',
  newPaperIds: ['paper-cell-diffusion', 'paper-med-vlm', 'paper-omics-agent'],
  highlightedTrends: [
    '多篇工作开始把检索模块接入科研推理链，而不是只做检索增强写作。',
    '医疗与脑科学方向都在强化“时间线建模”，关注疾病/认知过程而非单点分类。',
    '机器人实验平台从自动执行迈向主动决策，实验失败样本成为高价值监督信号。',
  ],
  relatedPaperIds: ['paper-omics-agent', 'paper-medical-kg', 'paper-robotic-lab'],
  researchGaps: [
    '显微图像与单细胞 pathway evidence 的统一评测集不足。',
    '纵向医疗数据中的事件时间线质量参差，临床可解释性缺少标准化模板。',
    '实验自动化论文多数缺乏失败日志建模，闭环优化仍偏经验驱动。',
  ],
  recommendedNextSteps: [
    '先用 20~30 篇核心论文搭建研究问题树，明确每条 Idea 的证据链长度。',
    '优先把已选 Idea 转为科研事项，再输出实验计划和风险清单。',
    '准备一份组会版 PPT 结构，把“研究空白—假设—验证方案”讲清楚。',
  ],
}

export const personalKnowledgeSnapshot: PersonalKnowledgeSnapshot = {
  myPapers: 42,
  myNotes: 18,
  myExperimentRecords: 11,
  subscribedPapers: 67,
  recentUpdates: [
    {
      id: 'update-01',
      title: '单细胞路径检索相关笔记补充了 3 篇最新工作',
      type: 'note',
      updatedAt: '10 分钟前',
    },
    {
      id: 'update-02',
      title: '纵向 CT 项目已同步最新病程时间线字段定义',
      type: 'paper',
      updatedAt: '32 分钟前',
    },
    {
      id: 'update-03',
      title: '机器人实验日志模板新增失败原因标签',
      type: 'experiment',
      updatedAt: '今天 09:30',
    },
    {
      id: 'update-04',
      title: 'Nature Machine Intelligence 订阅拉取到 4 篇候选论文',
      type: 'subscription',
      updatedAt: '今天 07:10',
    },
  ],
}

export const defaultResearchMatter: ResearchMatter = {
  id: 'matter-aifs-001',
  title: '构建显微扰动图像与 pathway retrieval 的可解释联动原型',
  field: 'AI for Science',
  objective: '验证显微图像与单细胞 pathway retrieval 联动后，是否能更稳定地产生可实验验证的药物作用假说。',
  hypothesis: '跨模态对齐后的细胞状态表示能提升假说生成的解释性，并减少无效候选。',
  sourcePaperIds: ['paper-cell-diffusion', 'paper-omics-agent'],
  status: 'planning',
  createdAt: '2026-05-23T14:10:00.000Z',
  updatedAt: '2026-05-24T08:10:00.000Z',
  outputs: ['experiment_plan', 'analysis_report', 'paper_draft', 'ppt'],
}

export const defaultExperimentPlan: ExperimentPlan = {
  objective: '在 2 周内完成跨模态假说生成原型的离线评估，确认是否值得进入 wet-lab 协作。',
  variables: ['图像编码器结构', 'pathway retrieval top-k', '解释性约束权重', '细胞状态伪标签策略'],
  data: ['公开细胞扰动图像集', '单细胞转录组对照集', '药物-通路知识表'],
  steps: [
    '整理 20 篇核心论文，统一抽取数据模式与评价指标。',
    '训练图像编码器与通路检索器，建立双塔基线。',
    '加入解释性约束并做 ablation，记录假说稳定性变化。',
    '输出实验候选清单，与湿实验同学确认最小验证集合。',
  ],
  risks: ['跨模态配对样本不足', '解释性指标缺少标准', 'wet-lab 验证周期长于预期'],
}

export const experimentNotebookEntries: ExperimentNotebookEntry[] = [
  {
    id: 'notebook-1',
    date: '2026-05-24',
    record: '完成 12 篇核心论文的结构化拆解，补齐了扰动图像与路径注释的字段映射。',
    observation: '解释性相关指标定义不统一，paper 间难以直接横向比较。',
    nextStep: '抽取 3 个统一指标，并在基线上先跑通。',
  },
  {
    id: 'notebook-2',
    date: '2026-05-23',
    record: '与实验平台同学确认了可优先复现的 2 个扰动任务。',
    observation: '实验可获取的数据批次较少，需要优先做小样本鲁棒性设计。',
    nextStep: '准备 failure analysis 模板，提前记录失配样本。',
  },
]

export const researchDataAnalysisSnapshot: ResearchDataAnalysisSnapshot = {
  uploadHint: '本地上传位仅作前端占位展示，可模拟接入 CSV、实验日志或图像特征文件。',
  analysisPlan: [
    '检查不同 pathway retrieval 深度下的假说一致性。',
    '比较加入解释性约束前后的 top hypothesis 质量变化。',
    '对失败样本做聚类，定位数据噪声与模型失配来源。',
  ],
  chartPlaceholders: ['假说质量趋势图', '不同 top-k 的可行性/新颖性对比图', '失败样本聚类热力图'],
  resultSummary: '当前 mock 结果显示：引入 pathway retrieval 后，假说新颖性提升明显，但可行性分布更分散，需要进一步收敛风险控制。',
}

export const researchWritingTasks: ResearchWritingTask[] = [
  {
    id: 'writing-report',
    label: '生成研究报告',
    description: '整理今日论文动态、研究空白与实验优先级，适合发送给导师或团队。',
    output: 'report',
  },
  {
    id: 'writing-outline',
    label: '生成论文大纲',
    description: '将当前科研事项拆成论文故事线，包括方法、实验、讨论与限制。',
    output: 'paper_outline',
  },
  {
    id: 'writing-ppt',
    label: '生成组会 PPT',
    description: '根据当前 Idea 与实验计划生成适合组会汇报的章节结构。',
    output: 'ppt',
  },
  {
    id: 'writing-proposal',
    label: '生成项目申请书',
    description: '输出项目背景、目标、研究方案和预期成果，适合立项申请。',
    output: 'proposal',
  },
]

export const localScienceCapabilities: LocalScienceCapability[] = [
  {
    id: 'capability-reading',
    title: '本地文献归纳器',
    description: '离线归纳论文结构、实验设定与局限，适合在没有外网的环境下做前期筛选。',
    status: 'ready',
    focus: ['摘要压缩', '结构提炼', '实验条件对比'],
  },
  {
    id: 'capability-planning',
    title: '实验设计助理',
    description: '基于当前 Idea 和研究目标生成变量、步骤和风险提示。',
    status: 'ready',
    focus: ['实验变量', '对照设计', '风险清单'],
  },
  {
    id: 'capability-analysis',
    title: '结果分析草稿器',
    description: '面向实验日志和数据摘要生成分析提纲，便于后续写报告或论文。',
    status: 'warming',
    focus: ['结论摘要', '图表建议', '异常点解释'],
  },
]

export function createDefaultResearchWorkspaceState(): ResearchWorkspaceState {
  return {
    selectedFieldId: researchFields[0].id,
    selectedIdeaId: researchIdeaCards[0].id,
    selectedMatterId: defaultResearchMatter.id,
    subscriptions: researchSubscriptions,
    matters: [defaultResearchMatter],
    selectedWritingTaskId: researchWritingTasks[0].id,
  }
}
